'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Empleado
    Public Property idEmpleado As Integer
    Public Property NombreCompleto As String
    Public Property idTipoIdentificacion As Short
    Public Property NumIdentificacion As String
    Public Property FechaIngreso As Nullable(Of Date)
    Public Property SalarioBase As Nullable(Of Decimal)
    Public Property Direccion As String
    Public Property Activo As Nullable(Of Boolean)

    Public Overridable Property TipoIdentificacion As TipoIdentificacion
    Public Overridable Property VacacionesDescansadas As ICollection(Of VacacionesDescansadas) = New HashSet(Of VacacionesDescansadas)
    Public Overridable Property ControlVacaciones As ICollection(Of ControlVacaciones) = New HashSet(Of ControlVacaciones)

End Class
