'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class VacacionesDescansadas
    Public Property idVacacionesDescansadas As Integer
    Public Property idEmpleado As Integer
    Public Property Fecha As Date
    Public Property Cantidad As Double
    Public Property Descripcion As String
    Public Property Activo As Nullable(Of Boolean)

    Public Overridable Property Empleado As Empleado

End Class
